import Head from 'next/head'
// head is for the page head or the website head just like in the HTML
import Image from 'next/image'
import Link from 'next/link'
// Image provides us optimized images by Next js it will load lazy images will only load when they are in the view port 
import Script from 'next/script'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div>
      <div className={styles.container}>
        {/* <StyledJSX /> */}
        {/* style JSX */}
   
        <Head>
          <title>Hunting Coder</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          {/* here we can add script as well you can also use script component given by NEXT js it is basically an extension of HTML script tag*/}
        </Head>
        {/* <Script strategy='lazyOnload' src='./text.js'> */}
          {/* https://nextjs.org/docs/basic-features/script */}

        {/* </Script> */}
        {/* <Image>

        </Image> */}
      
        <Image  className={styles.myImg} src="/coderImg.avif" width={"237"} height={"158"}/>
        <main className={styles.main}>
        <div className={styles.imagewrap}>
          {/* <Image className={styles.myImg} src="/homeimg.jfif" width={237} height={158}/> */}
          {/* <img className={styles.myImg} src="/homeimg.jfif" width={237} height={158} alt="hunting coder" /> */}
        </div>
        <h1 className={styles.title}>
          <span className='dummy'>&lt;HuntingCoder/&gt;</span>
        </h1>

        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web. Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic error voluptatum impedit!</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p className={styles.p}>JavaScript is the language used to design logic for the web</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>

      
      </div>
    </div>
  )
}
